name: CI

on:
  push:
    tags: ["*"] # Déclenchement pour tous les tags

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          generate_release_notes: true
          files: ./dist/main.js
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Update version in package.json
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${{ env.TAG_NAME }}
          echo "Updating version in package.json to $VERSION"
          npm version $VERSION --allow-same-version --no-git-tag-version

      - name: Commit changes
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add package.json
          git commit -m "Update version to ${{ env.TAG_NAME }}"

      - name: Push changes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: refs/heads/main
