name: Docs

on:
  push:
    tags: ["*"]
  pull_request:
      branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set tag name
        id: tag_name
        run: echo "TAG_NAME=${{ github.ref == 'refs/heads/main' && github.event_name == 'pull_request' && 'latest' || github.ref_name }}" >> $GITHUB_ENV

      - name: Install node modules
        run: npm install

      - name: Generate documentation
        run: npm run docs

      - name: Upload documentation to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs/jf-avatars/${{TAG_NAME}}/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4